#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd) && readonly script_dir
env_file="${script_dir}/.env" && readonly env_file

main() {
  set -eo pipefail
  sed -i '/^export mode=.*$/d' "$env_file"
  echo "export mode=notion" >>"$env_file"
}
main "$@"
